	  !********************************************************
	  !*                                                      *
	  !********************************************************
	  !************************* MEGA *************************
	  !********************************************************
	  !*                                                      *
	  !********* Meshfree Explicit Galerkin Analysis **********
	  !*                                                      *
	  !*                                                      *
	  !*                                                      *
	  !*     Copyright 2016 Michael C Hillman                 *
	  !*                                                      *
	  !********************************************************	  

	  

      SUBROUTINE VISCO_ELASTIC( PROPS, DLT, FMAT, & ! IN
								LSTRESS, H_STRESS, S_STRESS) ! OUT
	    !$ACC ROUTINE SEQ
	  !
	  ! FUNCTION OF THIS SUBROUTINE:
	  !
	  ! CALCULATE THE CORRECTED STRESS BY VISCO_ELASTIC MODEL
	  !
      USE FINT_FUNCTIONS
      !
	  IMPLICIT NONE
	  !
	  !GLOBAL IN-OUT
	  DOUBLE PRECISION, INTENT(IN):: PROPS(30)
	  DOUBLE PRECISION, INTENT(IN):: DLT
	  DOUBLE PRECISION, INTENT(IN):: FMAT(3,3)
	  
	  DOUBLE PRECISION, INTENT(OUT)::LSTRESS(6) ! IT IS TOTAL STRESS
	  DOUBLE PRECISION, INTENT(INOUT):: S_STRESS(6)! S
	  DOUBLE PRECISION, INTENT(INOUT):: H_STRESS(6)! h
	  !
  
	  DOUBLE PRECISION::YOUNG ! ELASTIC MODULUS
	  DOUBLE PRECISION::POISS ! POISS RATIO
	  DOUBLE PRECISION::ETA !VISCOSITY
	  DOUBLE PRECISION::RELAX_TIME ! RELAXATION TIME	  
	  DOUBLE PRECISION::BULKMOD
	  DOUBLE PRECISION::SHEARMOD
	  DOUBLE PRECISION::UNIT_VTENSOR(6)
	  
	  ! FOR FINITE STRAIN
	  DOUBLE PRECISION::J, FMAT_BAR(3,3), INV_FMAT_BAR(3,3), CMAT(3,3), CMAT_BAR(3,3), KIRCHHOFF_STRESS_BAR_MAT(3,3),BMAT_BAR(3,3),H_BAR_STRESS_MAT(3,3)
	  DOUBLE PRECISION::H_WAV_STRESS(6), KIRCHHOFF_STRESS_BAR_VEC(6), KIRCHHOFF_STRESS(6),H_BAR_STRESS_VEC(6)

	  UNIT_VTENSOR = (/1,1,1,0,0,0/)
	  
	  ! ASSIGN PROPERTY VARIABLES
	  POISS = PROPS(1)
	  YOUNG = PROPS(2)
	  ETA = PROPS(4)
	  BULKMOD = BULK_MOD(YOUNG,POISS)
	  SHEARMOD = SHEAR_MOD(YOUNG,POISS)
	  RELAX_TIME = ETA/SHEARMOD


		CALL DETERMINANT(FMAT, J)
		
		CMAT = MATMUL(TRANSPOSE(FMAT), FMAT)
		FMAT_BAR = J**(-1/3)*FMAT
		CMAT_BAR = J**(-2/3)*CMAT
		
		BMAT_BAR = MATMUL(FMAT_BAR,TRANSPOSE(FMAT_BAR))
		KIRCHHOFF_STRESS_BAR_VEC= SHEARMOD*DEV_PROJ(TENSOR_2_VTENSOR(BMAT_BAR)) ! KERCHHOFF STRESS_MAT
		KIRCHHOFF_STRESS_BAR_MAT = VTENSOR_2_TENSOR(KIRCHHOFF_STRESS_BAR_VEC) !INITIAL ELASTIC KIRCHHOFF STRESS

		CALL INVERSE(FMAT_BAR, 3, INV_FMAT_BAR)
		
		H_WAV_STRESS = EXP(-DLT/RELAX_TIME)*H_STRESS - EXP(-DLT/(2*RELAX_TIME))*S_STRESS
		S_STRESS = TENSOR_2_VTENSOR(MATMUL(MATMUL(INV_FMAT_BAR, KIRCHHOFF_STRESS_BAR_MAT), TRANSPOSE(INV_FMAT_BAR)))
		H_STRESS = H_WAV_STRESS + EXP(-DLT/(2*RELAX_TIME))*S_STRESS
		H_BAR_STRESS_MAT = MATMUL(MATMUL(FMAT_BAR, VTENSOR_2_TENSOR(H_WAV_STRESS)), TRANSPOSE(FMAT_BAR))
		H_BAR_STRESS_VEC = DEV_PROJ(TENSOR_2_VTENSOR(H_BAR_STRESS_MAT))
		
		KIRCHHOFF_STRESS = 0.5D0*BULKMOD*(J**2-1.0)*UNIT_VTENSOR + EXP(-DLT/(2*RELAX_TIME))*KIRCHHOFF_STRESS_BAR_VEC + H_BAR_STRESS_VEC
		
		LSTRESS = KIRCHHOFF_STRESS/J ! THE OUTER HAS TO BE ALTERED TOO: NO NEED TO USE ROTATION!

	  
	  RETURN
	  END SUBROUTINE
