       MODULE FINT_FUNCTIONS
    
       IMPLICIT NONE
    
    
       CONTAINS
       
       

      DOUBLE PRECISION FUNCTION VTENSOR_2_TENSOR(VTENSOR)
	  !
	  ! FUNCTION OF THIS FUNCTION:
	  !
	  ! CONVERT A VOIGT NOTATION TENSOR (VECTOR) TO A TENSOR (MATRIX)
	  !
	  IMPLICIT NONE
	  !
	  DIMENSION:: VTENSOR_2_TENSOR(3,3)
	  DOUBLE PRECISION, INTENT(IN):: VTENSOR(6)
	  
	  !VOIGT ORDERING:
      !XX, YY, ZZ, YZ, XZ, XY
	  !
	  VTENSOR_2_TENSOR(1,1) = VTENSOR(1) !XX
	  VTENSOR_2_TENSOR(2,2) = VTENSOR(2) !YY
	  VTENSOR_2_TENSOR(3,3) = VTENSOR(3) !ZZ
	  
	  VTENSOR_2_TENSOR(3,2) = VTENSOR(4) !YZ
	  VTENSOR_2_TENSOR(2,3) = VTENSOR(4) !YZ
	  
	  VTENSOR_2_TENSOR(1,3) = VTENSOR(5) !XZ
	  VTENSOR_2_TENSOR(3,1) = VTENSOR(5) !XZ
	  
	  VTENSOR_2_TENSOR(1,2) = VTENSOR(6) !XY
	  VTENSOR_2_TENSOR(2,1) = VTENSOR(6) !XY
		
	  RETURN
	  END FUNCTION
	  
	  
      DOUBLE PRECISION FUNCTION TENSOR_2_VTENSOR(TENSOR)
	  !
	  ! FUNCTION OF THIS FUNCTION:
	  !
	  ! CONVERT A TENSOR (MATRIX) TO A VOIGT NOTATION TENSOR (VECTOR)
	  !
	  IMPLICIT NONE
	  !
	  DOUBLE PRECISION, INTENT(IN):: TENSOR(3,3)
	  
	  DIMENSION:: TENSOR_2_VTENSOR(6)
	  
	  !VOIGT ORDERING:
      !XX, YY, ZZ, YZ, XZ, XY
	  !
	  TENSOR_2_VTENSOR(1) = TENSOR(1,1) !XX
	  TENSOR_2_VTENSOR(2) = TENSOR(2,2) !YY
	  TENSOR_2_VTENSOR(3) = TENSOR(3,3) !ZZ
	  
	  TENSOR_2_VTENSOR(4) = TENSOR(2,3) !YZ
	  TENSOR_2_VTENSOR(5) = TENSOR(1,3) !XZ
	  TENSOR_2_VTENSOR(6) = TENSOR(1,2) !XY
		
	  RETURN
	  END FUNCTION
    
	
	
      DOUBLE PRECISION FUNCTION TENSOR_NORM_STRAIN(VTENSOR)
	  !
	  ! FUNCTION OF THIS FUNCTION:
	  !
	  ! CONVERT A VOIGT NOTATION TENSOR (VECTOR) TO A TENSOR (MATRIX)
	  !
      ! NOTE THAT STRAIN IS A KINEMATIC VARIABLE, SO THERE SHOULD BE NO
      ! 2* ACCORDING TO THE VOIGT RULES (THERE  IS ALREADY A 2 THERE)
      !
	  IMPLICIT NONE
	  !
	  DOUBLE PRECISION, INTENT(IN):: VTENSOR(6)
	  DOUBLE PRECISION:: SIJSIJ
	  
	  !VOIGT ORDERING:
      !XX, YY, ZZ, YZ, XZ, XY
	  !
	  SIJSIJ =       VTENSOR(1)**2 + VTENSOR(2)**2 + VTENSOR(3)**2 + &
	               (VTENSOR(4)**2 + VTENSOR(5)**2 + VTENSOR(6)**2)
				   
	  TENSOR_NORM_STRAIN = SQRT(SIJSIJ)
		
	  RETURN
	  END FUNCTION
	  
      DOUBLE PRECISION FUNCTION TENSOR_NORM(VTENSOR)
	  !
	  ! FUNCTION OF THIS FUNCTION:
	  !
	  ! CONVERT A VOIGT NOTATION TENSOR (VECTOR) TO A TENSOR (MATRIX)
	  !
	  IMPLICIT NONE
	  !
	  DOUBLE PRECISION, INTENT(IN):: VTENSOR(6)
	  DOUBLE PRECISION:: SIJSIJ
	  
	  !VOIGT ORDERING:
      !XX, YY, ZZ, YZ, XZ, XY
	  !
	  SIJSIJ =       VTENSOR(1)**2 + VTENSOR(2)**2 + VTENSOR(3)**2 + &
	               2.0d0*(VTENSOR(4)**2 + VTENSOR(5)**2 + VTENSOR(6)**2)
				   
	  TENSOR_NORM = SQRT(SIJSIJ)
		
	  RETURN
	  END FUNCTION
      
      
      DOUBLE PRECISION FUNCTION J2(VTENSOR)
	  !
	  ! FUNCTION OF THIS FUNCTION:
	  !
	  ! CONVERT A VOIGT NOTATION TENSOR (VECTOR) TO A TENSOR (MATRIX)
	  !
	  IMPLICIT NONE
	  !
	  DOUBLE PRECISION, INTENT(IN):: VTENSOR(6)
	  DOUBLE PRECISION:: DEV_VTENSOR(6)
	  
	  DEV_VTENSOR = DEV_PROJ(VTENSOR)
	  ! 1/2 FACTOR IS NOT INCLUDED HERE
	  J2 =       DEV_VTENSOR(1)**2 + DEV_VTENSOR(2)**2 + DEV_VTENSOR(3)**2 + &
	               2.0d0*(DEV_VTENSOR(4)**2 + DEV_VTENSOR(5)**2 + DEV_VTENSOR(6)**2)
				   
		
	  RETURN
	  END FUNCTION
	  
	  
      DOUBLE PRECISION FUNCTION DEV_PROJ(VTENSOR)
	  !
	  ! FUNCTION OF THIS FUNCTION:
	  !
	  ! CONVERT A VOIGT NOTATION TENSOR (VECTOR) TO A TENSOR (MATRIX)
	  !
	  IMPLICIT NONE
	  !
	  DOUBLE PRECISION, INTENT(IN):: VTENSOR(6)
	  DIMENSION:: DEV_PROJ(6)
	  DOUBLE PRECISION:: SIGKK
	  
	  !VOIGT ORDERING:
      !XX, YY, ZZ, YZ, XZ, XY
	  !
	  
	  SIGKK = VTENSOR(1)+ VTENSOR(2)+VTENSOR(3)
	  
	  
	  DEV_PROJ(1) = VTENSOR(1) - SIGKK/3.0d0
	  DEV_PROJ(2) = VTENSOR(2) - SIGKK/3.0d0
	  DEV_PROJ(3) = VTENSOR(3) - SIGKK/3.0d0
	  DEV_PROJ(4) = VTENSOR(4) 
	  DEV_PROJ(5) = VTENSOR(5) 
	  DEV_PROJ(6) = VTENSOR(6) 
		
	  RETURN
	  END FUNCTION
	  
	  			
      DOUBLE PRECISION FUNCTION SPHR_PROJ(VTENSOR)
	  !
	  ! FUNCTION OF THIS FUNCTION:
	  !
	  ! CONVERT A VOIGT NOTATION TENSOR (VECTOR) TO A TENSOR (MATRIX)
	  !
	  IMPLICIT NONE
	  !
	  DOUBLE PRECISION, INTENT(IN):: VTENSOR(6)
	  DIMENSION:: SPHR_PROJ(6)
	  DOUBLE PRECISION:: SIGKK
	  
	  !VOIGT ORDERING:
      !XX, YY, ZZ, YZ, XZ, XY
	  !
	  
	  SIGKK = VTENSOR(1)+ VTENSOR(2)+VTENSOR(3)
	  
	  
	  SPHR_PROJ(1) =  - SIGKK/3.0d0
	  SPHR_PROJ(2) =  - SIGKK/3.0d0
	  SPHR_PROJ(3) =  - SIGKK/3.0d0
	  SPHR_PROJ(4) = 0.0d0
	  SPHR_PROJ(5) = 0.0d0
	  SPHR_PROJ(6) = 0.0d0
		
	  RETURN
	  END FUNCTION
	  
      DOUBLE PRECISION FUNCTION BULK_MOD(YOUNG,POISS)
	  !
	  ! FUNCTION OF THIS FUNCTION:
	  !
	  ! GIVEN E AND V, COMPUTE BULK MODULUS
	  !
	  IMPLICIT NONE
	  !
	  DOUBLE PRECISION, INTENT(IN):: YOUNG,POISS
	  
	  
	  BULK_MOD = YOUNG/(3.0d0*(1.0d0-2.0d0*POISS))
		
	  RETURN
	  END FUNCTION
	  
	  
	  
      DOUBLE PRECISION FUNCTION SHEAR_MOD(YOUNG,POISS)
	  !
	  ! FUNCTION OF THIS FUNCTION:
	  !
	  ! GIVEN E AND V, COMPUTE SHEAR MODULUS
	  !
	  IMPLICIT NONE
	  !
	  DOUBLE PRECISION, INTENT(IN):: YOUNG,POISS
	  
	  
		SHEAR_MOD = YOUNG/(2.0d0*(1.0d0+POISS))
		
	  RETURN
	  END FUNCTION
	  
	  
	  
      DOUBLE PRECISION FUNCTION LAMDA_MOD(BULK,SHEAR)
	  !
	  ! FUNCTION OF THIS FUNCTION:
	  !
	  ! GIVEN E AND V, COMPUTE SHEAR MODULUS
	  !
	  IMPLICIT NONE
	  !
	  DOUBLE PRECISION, INTENT(IN):: BULK,SHEAR
	  
	  
		LAMDA_MOD = BULK - 2.0d0*SHEAR/3.0d0
		
	  RETURN
	  END FUNCTION
	  
	  
	  
	  
	  DOUBLE PRECISION FUNCTION FORM_CMAT(LPROP)
	  !
	  ! FUNCTION OF THIS FUNCTION:
	  !
	  ! FORM AN ISOTROPIC ELASTIC CONSITUATIVE MATRIX
	  !
	  IMPLICIT NONE
	  !
	  DIMENSION:: FORM_CMAT(6,6)
	  DOUBLE PRECISION, INTENT(IN):: LPROP(30)
      DOUBLE PRECISION:: LAMDA,MU,LAMDA_PLUS_2MU
	  INTEGER:: I,J
	  
	  LAMDA = LPROP(28)
	  MU = LPROP(29)
	  LAMDA_PLUS_2MU = LPROP(30) 
				  
	  FORM_CMAT = 0.0d0
      
	  FORM_CMAT(1,1) = LAMDA_PLUS_2MU
	  FORM_CMAT(2,2) = LAMDA_PLUS_2MU
	  FORM_CMAT(3,3) = LAMDA_PLUS_2MU
	  FORM_CMAT(4,4) = MU
	  FORM_CMAT(5,5) = MU
	  FORM_CMAT(6,6) = MU
	  
	  FORM_CMAT(1,2) = LAMDA
	  FORM_CMAT(2,1) = LAMDA
	  
	  FORM_CMAT(1,3) = LAMDA
	  FORM_CMAT(3,1) = LAMDA
	  
	  FORM_CMAT(3,2) = LAMDA
	  FORM_CMAT(2,3) = LAMDA
	  
	  RETURN
	  END FUNCTION
       
       
       END MODULE 